# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: æ´›ç«¹çš„åšå®¢
subtitle: çœŸç†æ— ç©·ï¼Œä¸€å¯¸æ¬¢å–œã€‚
description: æ´›ç«¹çš„ä¸ªäººåšå®¢ï¼Œè®°å½•åˆ†äº«ç¾å¥½ç”Ÿæ´»ã€å­¦ä¹ ç¬”è®°ã€å·¥ä½œç»éªŒã€ç¼–ç¨‹å¼€å‘æŠ€å·§ã€åŠ å¯†æŠ•ç ”ã€é‡‘èçŸ¥è¯†ï¼Œæ€»ä¹‹åœ¨æ´›ç«¹çš„åšå®¢ä½ ä¼šå‘ç°äº†ä¸€ä¸ªå…´è¶£å¹¿æ³›ä¸”çˆ±æŠ˜è…¾çš„ç¨‹åºå‘˜ã€‚
keywords:
  - è®¡ç®—æœº
  - äº’è”ç½‘
  - ç¨‹åºå‘˜
  - ç§‘å­¦ä¸Šç½‘
  - åŠ å¯†æŠ•ç ”
  - ç¼–ç¨‹å¼€å‘
  - å­¦ä¹ ç¬”è®°
  - chatgpt
  - å‰ç«¯å¼€å‘
  - æ´›ç«¹
  - ç½—å°é»‘æˆ˜è®°
  - æ— é™
  - é£æ¯
author: æ´›ç«¹
language: zh-TW
timezone: Asia/Taipei

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://youngjuning.js.org
permalink: :hash/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
sitemap:
  path: sitemap.xml
feed:
  type: Atom
  path: atom.xml
  limit: 20
nofollow:
  enable: true
  field: site
# ç»Ÿè®¡å›¾è¡¨ï¼Œæ”¯æŒå‘å¸ƒæ–‡ç« ç»Ÿè®¡ã€å‘å¸ƒæ—¥å†ã€Topæ ‡ç­¾ç»Ÿè®¡ã€åˆ†ç±»ç»Ÿè®¡ã€åˆ†ç±»é›·è¾¾ã€‚
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # æ˜¯å¦å¯ç”¨åŠŸèƒ½
  postsChart:
    title: æ–‡ç« å‘å¸ƒç»Ÿè®¡ # è®¾ç½®æ–‡ç« å‘å¸ƒç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
    interval: 1 # æ¨ªåæ ‡é—´éš”
  tagsChart:
    title: Top 10 æ ‡ç­¾ç»Ÿè®¡ # è®¾ç½®æ ‡ç­¾ç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
    interval: 1 # æ¨ªåæ ‡é—´éš”
  postsCalendar_Title: #æ–‡ç« å‘å¸ƒæ—¥å† # è®¾ç½®å‘å¸ƒæ—¥å†çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
  categoriesChart_Title: # è®¾ç½®åˆ†ç±»ç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
  categoriesRadar_Title: # è®¾ç½®åˆ†ç±»é›·è¾¾çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
# https://github.com/xiazeyu/live2d-widget-models
# https://www.cnblogs.com/strengthen/p/11112215.html
# https://imbhj.com/599f1d72/
live2d:
  enable: false
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-miku
  display:
    position: left
    width: 200
    height: 400
  mobile:
    show: false
douban:
  user: youngjuning
  builtin: true
  book:
    title: 'é‚£äº›å¹´ï¼Œæˆ‘çœ‹è¿‡çš„ä¹¦ğŸ“š'
    quote: 'ä¹¦ä¸­è‡ªæœ‰é¢œå¦‚ç‰ï¼Œä¹¦ä¸­è‡ªæœ‰é»„é‡‘å±‹'
    meta: true
    comments: true
    top_img: https://cdn.jsdelivr.net/gh/youngjuning/images/202109241451349.png
    aside: true
    path: books
    limit:
  movie:
    title: 'é‚£äº›å¹´ï¼Œæˆ‘çœ‹è¿‡çš„ç”µå½±ğŸ¬'
    quote: 'äººç”Ÿå¦‚æˆï¼Œæˆå¦‚äººç”Ÿ'
    meta: true
    comments: true
    top_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/movie.jpg
    aside: true
    path: movies
    limit:
  timeout: 10000
bangumi:
  enable: true
  source: bili
  path: bangumi/
  vmid: 52457741
  title: 'è¿½ç•ªåˆ—è¡¨'
  quote: 'ç”Ÿå‘½ä¸æ¯ï¼Œè¿½ç•ªä¸æ­¢ï¼'
  show: 1
minify:
  preview: false ## æœ¬åœ°é¢„è§ˆæ—¶æ˜¯å¦å‹ç¼©
  exclude: ['*.min.*']
  js:
    enable: true
    ## è¯¦ç»†é…ç½®: https://github.com/terser/terser#minify-options
    options: {}
  css:
    enable: true
    ## è¯¦ç»†é…ç½®: https://github.com/clean-css/clean-css#compatibility-modes
    options: {}
  html:
    enable: true
    ## è¯¦ç»†é…ç½®: https://github.com/kangax/html-minifier#options-quick-reference
    options:
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  image:
    enable: true
    svg:
      enable: true
      ## è¯¦ç»†é…ç½®: https://github.com/imagemin/imagemin-svgo#imageminsvgooptionsbuffer
      options: {}
    jpg:
      enable: true
      ## è¯¦ç»†é…ç½®: https://github.com/imagemin/imagemin-jpegtran#options
      options: {}
    png:
      enable: true
      ## è¯¦ç»†é…ç½®: https://github.com/imagemin/imagemin-pngquant#options
      options: {}
    gif:
      enable: true
      ## è¯¦ç»†é…ç½®: https://www.npmjs.com/package/imagemin-gifsicle#options
      options: {}
    webp:
      enable: true
      ## è¯¦ç»†é…ç½®: https://github.com/imagemin/imagemin-webp#options
      options: {}
  font:
    enable: true
    ## è¯¦ç»†é…ç½®: https://github.com/Lete114/fontmin-spider#api
    options: {}
# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  timemode: date #date/updated
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper cssä¾èµ–
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper jsä¾èµ–
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # é€‚é…ä¸»é¢˜æ ·å¼è¡¥ä¸
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiperåˆå§‹åŒ–æ–¹æ³•
# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  issues: false #issuesæ ‡ç­¾ä¾èµ–æ³¨å…¥å¼€å…³
  link:
    placeholder: https://cdn.jsdelivr.net/gh/youngjuning/images@main/1680450378978.png #link_cardæ ‡ç­¾é»˜è®¤çš„å›¾æ ‡å›¾ç‰‡
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #åŠ¨ç”»æ ‡ç­¾animaçš„ä¾èµ–
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issuesæ ‡ç­¾ä¾èµ–
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issuesæ ‡ç­¾ä¾èµ–
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js #å‚çœ‹https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
